name: CICD pipeline 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t node-app .
      - name: Run the container
        run: docker run -d -p 3000:3000 node-app
